### ISSUE TITLE
Issue created

### ISSUE THREAD

**Issue by Ham159** [Ham159/Modern-Cloud#1]
Hello,
I have created a Issue please assign I will be doing April work or we can continue along as step by step.
This is a step two working on the project.
Please assign this Issue and we can communicate like that or you can email me at hahmed9@stlcc.edu.

Thank you

**Comment by AJisHere88** [comment]
I understand. I will begin working as Alex and communicate with you as I complete things. Thank you.

**Comment by Ham159** [comment]
Awsome I am attaching the steps and sceenshots took so far. Please letme know if you have any question.
[Final Project.docx](https://github.com/Ham159/Modern-Cloud/files/10805000/Final.Project.docx)
